# This is PLAY-01
- name: PLAY-01
  hosts: web
  tasks: 
  - name: PLAY-01 TASK-01  #here it is called list of tasks.
    ansible.builtin.debug:
      msg: "This is from PLAY-01 and TASK-01"


# This is PLAY-02
- name: PLAY-02
  hosts: web
  tasks: 
  - name: PLAY-02 TASK-01  #here it is called list of tasks.
    ansible.builtin.debug:
      msg: "This is from PLAY-02 and TASK-01"