- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: "COURSE"
    prompt: please enter the course name
    private: false #its not a confidential.
  - name: "DURATION"
    prompt: please enter the duration
    private: false #its not a confidential.
  - name: "TRAINER"
    prompt: please enter the trainer name
    private: false #its not a confidential.
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"