- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS from PLAY level"
    DURATION: "120 Hrs"
    TRAINER: "Sivakumar Reddy"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: "COURSE"
  #   prompt: please enter the course name
  #   private: false #its not a confidential.
  # - name: "DURATION"
  #   prompt: please enter the duration
  #   private: false #its not a confidential.
  # - name: "TRAINER"
  #   prompt: please enter the trainer name
  #   private: false #its not a confidential.
  tasks:
  - name: print the information
    # vars:
    #   COURSE: "DevOps with AWS from TASK level"
    #   DURATION: "120 Hrs"
    #   TRAINER: "Sivakumar Reddy"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

#1st preference is always command line/args
#2nd preference is TASK level
#3rd preference is Files
#4th preference is prompt level
#5th preference is
#6th preference is