- name: loops demo
  hosts: local
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello {{item}}" #"ITEM" is by default Reserved keyword

      loop: # Loop is not part of the module.
      - Ramesh
      - Suresh
      - Raheem
      - Siva