- name: Loops
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.present}}"

      loop:
      - { name: 'mysql' , state: 'present' }
      - { name: 'nginx' , state: 'absent' }
      - { name: 'postfix' , state: 'absent' }
      - { name: 'httpd' ,state: 'present' }