- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the command
      ansible.builtin.shell: ls -ltr > /tmp/output.txt # 'Shell module' will login to the server and execute the command inside.
                                                       # 'Command module' just issues the command.
                                                       # Compared to both, 'Command module' is secured.
    
    - name: check the process
      ansible.builtin.command: ps -ef | grep ssh
      register: output